# l10n.yaml
arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-dir: lib/l10n/generated
preferred-supported-locales: ["en", "zh_CN", "zh_TW", "ja", "ko", "de", "fr", "es", "pt", "ar"]