// lib/widgets/summary/sections/report_header_section.dart
import 'package:flutter/material.dart';
import '../../../config/design_system/summary_theme.dart';
import '../../../utils/shared/summary_data_calculator.dart';
import '../summary_controls_widget.dart';

/// Report Header Section - Main title and report information
class ReportHeaderSection extends StatelessWidget {
  final SummaryPeriod period;

  const ReportHeaderSection({
    super.key,
    required this.period,
  });

  @override
  Widget build(BuildContext context) {
    final now = DateTime.now();
    final reportId = 'FR-${now.year}${now.month.toString().padLeft(2, '0')}${now.day.toString().padLeft(2, '0')}-${now.hour.toString().padLeft(2, '0')}${now.minute.toString().padLeft(2, '0')}${now.second.toString().padLeft(2, '0')}';

    return Column(
      children: [
        // Main Header with Gradient
        Container(
          width: double.infinity,
          padding: const EdgeInsets.all(20),
          decoration: SummaryTheme.headerDecoration,
          child: Column(
            children: [
              Text(
                'FITNESS PROGRESS REPORT',
                style: SummaryTheme.reportTitle,
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 8),
              Text(
                'Generated by Food LLM',
                style: SummaryTheme.reportSubtitle,
                textAlign: TextAlign.center,
              ),
            ],
          ),
        ),

        const SizedBox(height: 16),

        // Report Information Card
        Container(
          width: double.infinity,
          padding: const EdgeInsets.all(SummaryTheme.sectionPadding),
          decoration: SummaryTheme.sectionDecoration,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  const Icon(Icons.description, size: 18, color: SummaryTheme.primary),
                  const SizedBox(width: 8),
                  Text('REPORT INFORMATION', style: SummaryTheme.sectionHeader),
                ],
              ),
              const Divider(height: SummaryTheme.dividerHeight),
              _buildInfoRow('Period', SummaryDataCalculator.getPeriodTitle(period)),
              _buildInfoRow('Date Range', SummaryDataCalculator.getPeriodSubtitle(period)),
              _buildInfoRow('Generated', SummaryDataCalculator.formatDate(now)),
              _buildInfoRow('Report ID', reportId),
            ],
          ),
        ),
      ],
    );
  }

  Widget _buildInfoRow(String label, String value) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(label, style: SummaryTheme.infoLabel),
          Text(value, style: SummaryTheme.infoValue),
        ],
      ),
    );
  }
}
