// lib/widgets/summary/sections/report_footer_section.dart
import 'package:flutter/material.dart';
import '../../../config/design_system/summary_theme.dart';

/// Report Footer Section - Disclaimer and branding
class ReportFooterSection extends StatelessWidget {
  const ReportFooterSection({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(SummaryTheme.sectionPadding),
      decoration: SummaryTheme.footerDecoration,
      child: Column(
        children: [
          Text(
            'Report generated by Food LLM v1.0',
            style: SummaryTheme.bodySmall.copyWith(fontWeight: FontWeight.w600),
            textAlign: TextAlign.center,
          ),
          const SizedBox(height: 8),
          Text(
            'Disclaimer: This report contains estimates based on user-provided data. '
            'Consult healthcare professionals for medical advice. Body composition '
            'estimates use standard formulas and may vary from clinical measurements.',
            style: SummaryTheme.bodySmall.copyWith(fontSize: 9),
            textAlign: TextAlign.center,
          ),
        ],
      ),
    );
  }
}
