// lib/widgets/summary/sections/report_footer_section.dart
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../../config/design_system/widget_theme.dart';
import '../../../config/design_system/typography.dart';
import '../../../providers/theme_provider.dart';

/// Report Footer Section - Disclaimer and branding
class ReportFooterSection extends StatelessWidget {
  const ReportFooterSection({super.key});

  @override
  Widget build(BuildContext context) {
    return Consumer<ThemeProvider>(
      builder: (context, themeProvider, _) {
        final textColor = AppWidgetTheme.getTextColor(themeProvider.selectedGradient);
        final borderColor = AppWidgetTheme.getBorderColor(
          themeProvider.selectedGradient,
          AppWidgetTheme.cardBorderOpacity,
        );

        return Container(
          width: double.infinity,
          padding: EdgeInsets.all(AppWidgetTheme.spaceXL),
          decoration: BoxDecoration(
            color: Colors.transparent,
            border: Border.all(
              color: borderColor,
              width: AppWidgetTheme.cardBorderWidth,
            ),
            borderRadius: BorderRadius.circular(AppWidgetTheme.cardBorderRadius),
          ),
          child: Column(
            children: [
              Text(
                'Report generated by OptiMate v1.0',
                style: AppTypography.bodySmall.copyWith(
                  fontWeight: FontWeight.w600,
                  color: textColor,
                ),
                textAlign: TextAlign.center,
              ),
              SizedBox(height: AppWidgetTheme.spaceSM),
              Text(
                'Disclaimer: This report contains estimates based on user-provided data. '
                'Consult healthcare professionals for medical advice. Body composition '
                'estimates use standard formulas and may vary from clinical measurements.',
                style: AppTypography.bodySmall.copyWith(
                  fontSize: AppWidgetTheme.fontSizeXS,
                  color: textColor.withValues(alpha: AppWidgetTheme.opacityHigher),
                ),
                textAlign: TextAlign.center,
              ),
            ],
          ),
        );
      },
    );
  }
}
