// lib/widgets/summary/sections/report_header_section.dart
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../../config/design_system/widget_theme.dart';
import '../../../config/design_system/typography.dart';
import '../../../config/constants/app_constants.dart';
import '../../../data/models/user_profile.dart';
import '../../../providers/theme_provider.dart';
import '../../../utils/shared/summary_data_calculator.dart';
import '../summary_controls_widget.dart';

/// Combined Report Header + Client Info Section
/// Glassmorphism design with frosted glass effect
class ReportHeaderSection extends StatelessWidget {
  final SummaryPeriod period;
  final UserProfile? profile;

  const ReportHeaderSection({
    super.key,
    required this.period,
    required this.profile,
  });

  @override
  Widget build(BuildContext context) {
    return Consumer<ThemeProvider>(
      builder: (context, themeProvider, _) {
        final now = DateTime.now();

        return _buildGlassCard(
          child: Center(
            child: Column(
              children: [
                // Title: User Name + App Name + Report
                Text(
                  '${(profile?.name ?? 'User').toUpperCase()} ${AppConstants.appDisplayName} REPORT',
                  style: AppTypography.displayLarge.copyWith(
                    fontSize: AppWidgetTheme.fontSizeXL,
                    fontWeight: FontWeight.bold,
                    color: Colors.white,
                    letterSpacing: 2.0,
                  ),
                  textAlign: TextAlign.center,
                ),
                const SizedBox(height: AppWidgetTheme.spaceSM),

                // Period Type with Icon
                Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Icon(
                      _getPeriodIcon(period),
                      size: AppWidgetTheme.iconSizeSmall,
                      color: Colors.white.withValues(alpha: 0.7),
                    ),
                    const SizedBox(width: AppWidgetTheme.spaceXS),
                    Text(
                      SummaryDataCalculator.getPeriodTitle(period),
                      style: AppTypography.bodyMedium.copyWith(
                        fontSize: AppWidgetTheme.fontSizeMS,
                        color: Colors.white.withValues(alpha: 0.7),
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: AppWidgetTheme.spaceXS),

                // Date Range
                Text(
                  SummaryDataCalculator.getPeriodSubtitle(period),
                  style: AppTypography.bodySmall.copyWith(
                    fontSize: AppWidgetTheme.fontSizeSM,
                    color: Colors.white.withValues(alpha: 0.6),
                  ),
                  textAlign: TextAlign.center,
                ),
                const SizedBox(height: AppWidgetTheme.spaceXS),

                // Generated Date
                Text(
                  'Generated: ${SummaryDataCalculator.formatDate(now)}',
                  style: AppTypography.bodySmall.copyWith(
                    fontSize: AppWidgetTheme.fontSizeSM,
                    color: Colors.white.withValues(alpha: 0.6),
                  ),
                  textAlign: TextAlign.center,
                ),
                const SizedBox(height: AppWidgetTheme.spaceSM),

                // Footer
                Text(
                  'Generated by Food LLM',
                  style: AppTypography.bodySmall.copyWith(
                    fontSize: AppWidgetTheme.fontSizeXS,
                    color: Colors.white.withValues(alpha: 0.5),
                    fontStyle: FontStyle.italic,
                  ),
                  textAlign: TextAlign.center,
                ),
              ],
            ),
          ),
        );
      },
    );
  }

  Widget _buildGlassCard({required Widget child}) {
    return Container(
      width: double.infinity,
      margin: const EdgeInsets.symmetric(horizontal: AppWidgetTheme.spaceXL),
      padding: const EdgeInsets.all(AppWidgetTheme.spaceXL),
      decoration: BoxDecoration(
        color: Colors.black.withValues(alpha: 0.15),
        borderRadius: BorderRadius.circular(AppWidgetTheme.cardBorderRadius),
        border: Border.all(
          color: Colors.black.withValues(alpha: 0.10),
          width: 2.5,
        ),
      ),
      child: child,
    );
  }

  IconData _getPeriodIcon(SummaryPeriod period) {
    switch (period) {
      case SummaryPeriod.daily:
        return Icons.today;
      case SummaryPeriod.weekly:
        return Icons.view_week;
      case SummaryPeriod.monthly:
        return Icons.calendar_month;
    }
  }
}
