// lib/widgets/summary/sections/report_footer_section.dart
import 'package:flutter/material.dart';
import '../../../config/design_system/widget_theme.dart';
import '../../../config/design_system/typography.dart';
import '../../common/frosted_glass_card.dart';

/// Report Footer Section - Disclaimer and branding
class ReportFooterSection extends StatelessWidget {
  const ReportFooterSection({super.key});

  @override
  Widget build(BuildContext context) {
    return FrostedGlassCard(
      child: Column(
        children: [
          Text(
            'Report generated by OptiMate v1.0',
            style: AppTypography.bodySmall.copyWith(
              fontWeight: FontWeight.w600,
              color: Colors.white,
            ),
            textAlign: TextAlign.center,
          ),
          const SizedBox(height: AppWidgetTheme.spaceSM),
          Text(
            'Disclaimer: This report contains estimates based on user-provided data. '
            'Consult healthcare professionals for medical advice. Body composition '
            'estimates use standard formulas and may vary from clinical measurements.',
            style: AppTypography.bodySmall.copyWith(
              fontSize: AppWidgetTheme.fontSizeXS,
              color: Colors.white.withValues(alpha: AppWidgetTheme.opacityHigher),
            ),
            textAlign: TextAlign.center,
          ),
        ],
      ),
    );
  }
}
