// lib/widgets/summary/sections/report_header_section.dart
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../../config/design_system/widget_theme.dart';
import '../../../config/design_system/typography.dart';
import '../../../providers/theme_provider.dart';
import '../../../utils/shared/summary_data_calculator.dart';
import '../summary_controls_widget.dart';

/// Report Header Section - Main title and report information
/// Uses professional white background with ReportColors
class ReportHeaderSection extends StatelessWidget {
  final SummaryPeriod period;

  const ReportHeaderSection({
    super.key,
    required this.period,
  });

  @override
  Widget build(BuildContext context) {
    return Consumer<ThemeProvider>(
      builder: (context, themeProvider, _) {
        // Keep theme color for icon accent
        final iconAccentColor = AppWidgetTheme.getTextColor(themeProvider.selectedGradient);

        final now = DateTime.now();
        final reportId = 'FR-${now.year}${now.month.toString().padLeft(2, '0')}${now.day.toString().padLeft(2, '0')}-${now.hour.toString().padLeft(2, '0')}${now.minute.toString().padLeft(2, '0')}${now.second.toString().padLeft(2, '0')}';

        return Column(
          children: [
            // Main Header with Border
            Container(
              width: double.infinity,
              margin: const EdgeInsets.symmetric(horizontal: AppWidgetTheme.spaceXL),
              padding: const EdgeInsets.all(AppWidgetTheme.spaceXL),
              decoration: BoxDecoration(
                color: ReportColors.background,
                border: Border.all(
                  color: ReportColors.border,
                  width: 1.5,
                ),
                borderRadius: BorderRadius.circular(AppWidgetTheme.cardBorderRadius),
              ),
              child: Column(
                children: [
                  Text(
                    'FITNESS PROGRESS REPORT',
                    style: AppTypography.displayLarge.copyWith(
                      fontSize: AppWidgetTheme.fontSizeXL,
                      fontWeight: FontWeight.bold,
                      color: ReportColors.textPrimary,
                      letterSpacing: 1.5,
                    ),
                    textAlign: TextAlign.center,
                  ),
                  const SizedBox(height: AppWidgetTheme.spaceSM),
                  Text(
                    'Generated by Food LLM',
                    style: AppTypography.bodyMedium.copyWith(
                      fontSize: AppWidgetTheme.fontSizeMS,
                      color: ReportColors.textSecondary,
                    ),
                    textAlign: TextAlign.center,
                  ),
                ],
              ),
            ),

            const SizedBox(height: AppWidgetTheme.spaceXL),

            // Report Information Card
            Container(
              width: double.infinity,
              margin: const EdgeInsets.symmetric(horizontal: AppWidgetTheme.spaceXL),
              padding: const EdgeInsets.all(AppWidgetTheme.spaceXL),
              decoration: BoxDecoration(
                color: ReportColors.background,
                border: Border.all(
                  color: ReportColors.border,
                  width: 1.5,
                ),
                borderRadius: BorderRadius.circular(AppWidgetTheme.cardBorderRadius),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      Icon(
                        Icons.description,
                        size: AppWidgetTheme.iconSizeMedium,
                        color: iconAccentColor, // Keep theme color for visual interest
                      ),
                      const SizedBox(width: AppWidgetTheme.spaceSM),
                      Text(
                        'REPORT INFORMATION',
                        style: AppTypography.displaySmall.copyWith(
                          fontSize: AppWidgetTheme.fontSizeML,
                          fontWeight: FontWeight.bold,
                          color: ReportColors.textPrimary,
                          letterSpacing: 0.5,
                        ),
                      ),
                    ],
                  ),
                  const Divider(
                    height: AppWidgetTheme.spaceXL,
                    color: ReportColors.divider,
                  ),
                  _buildInfoRow('Period', SummaryDataCalculator.getPeriodTitle(period)),
                  _buildInfoRow('Date Range', SummaryDataCalculator.getPeriodSubtitle(period)),
                  _buildInfoRow('Generated', SummaryDataCalculator.formatDate(now)),
                  _buildInfoRow('Report ID', reportId),
                ],
              ),
            ),
          ],
        );
      },
    );
  }

  Widget _buildInfoRow(String label, String value) {
    return Padding(
      padding: const EdgeInsets.only(bottom: AppWidgetTheme.spaceSM),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(
            label,
            style: AppTypography.bodyMedium.copyWith(
              fontSize: AppWidgetTheme.fontSizeSM,
              color: ReportColors.textSecondary,
            ),
          ),
          Text(
            value,
            style: AppTypography.bodyMedium.copyWith(
              fontSize: AppWidgetTheme.fontSizeSM,
              fontWeight: FontWeight.w600,
              color: ReportColors.textPrimary,
            ),
          ),
        ],
      ),
    );
  }
}
